default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres


development:
  <<: *default
  database: exchange-coin_development


test:
  <<: *default
  database: exchange-coin_test
 

production:
  <<: *default
  database: exchange-coin_production
  username: exchange-coin
  password: <%= ENV['EXCHANGE_DATABASE_PASSWORD'] %>